admin/config/routes.rb
Admin::Engine.routes.draw do
  resources :movies, :actors
  root to: 'dashboard#index'
end

admin/app/models/admin/casting_detail.rb
module Admin
  ##
  # Details of a casting including the inverse object id and the role being
  # cast for.
  class CastingDetail
    include Virtus.value_object
    include ActiveModel::Validations

    values do
      attribute :id, Integer
      attribute :role, String
    end

    validates_numericality_of :id, only_integer: true
    validates_presence_of :role
  end
end

admin/app/models/admin/casting_transaction.rb
module Admin
  ##
  # Transaction to create a batch of castings for a subject (movie or actor) to many
  # inverse objects (actor or movies).
  class CastingTransaction
    include Virtus.model
    include ActiveModel::Validations

    attribute :subject_type, String
    attribute :subject_id, Integer
    attribute :casting_details, Set[CastingDetail], default: Set.new

    validates_inclusion_of :subject_type, in: %w{Movie Actor}
    validates_presence_of :subject_id
    validates_length_of :casting_details, minimum: 1

    def valid?
      super && begin
        !casting_details.detect{|cd| !cd.valid?}
      end
    end

    def save!
      ActiveRecord::Base.transaction do
        raise ValidationFailed unless valid?
        casting_details.each do |casting_detail|
          create_casting_from(casting_detail)
        end
      end
    end

    private
    def create_casting_from(casting_detail)
      casting = Core::Casting.new
      if movie_subject?
        casting.movie_id = subject_id
        casting.actor_id = casting_detail.id
        casting.role = casting_detail.role
      else
        casting.actor_id = subject_id
        casting.movie_id = casting_detail.id
        casting.role = casting_detail.role
      end
      casting.save!
    end

    def movie_subject?
      subject_type == 'Movie'
    end

    def actor_subject?
      subject_type == 'Actor'
    end

    class ValidationFailed < StandardError
    end
  end
end

admin/app/controllers/admin/actors_controller.rb
require_dependency "admin/application_controller"

module Admin
  class ActorsController < ApplicationController
    before_filter :lookup_actor, only: [:edit, :update, :destroy]

    def index
      @actors = Core::Actor.all
    end

    def new
      @actor = Core::Actor.new
    end

    def create
      @actor = Core::Actor.new(actor_params)
      if @actor.save
        redirect_to action: :index
      else
        render :new
      end
    end

    def edit
    end

    def update
      if @actor.update(actor_params)
        redirect_to action: :index
      else
        render :edit
      end
    end

    def destroy
      @actor.destroy!
      redirect_to action: :index
    end

    private
      def actor_params
        params.require(:actor).permit(:first_name, :last_name)
      end

      def lookup_actor
        @actor = Core::Actor.find(params[:id])
      end
  end
end

admin/app/controllers/admin/admin_controller.rb
require_dependency "admin/application_controller"

module Admin
  class AdminController < ApplicationController
    def index
      require 'pry'; binding.pry
    end
  end
end

admin/app/controllers/admin/application_controller.rb
module Admin
  class ApplicationController < ActionController::Base
  end
end

admin/app/controllers/admin/dashboard_controller.rb
require_dependency "admin/application_controller"

module Admin
  class DashboardController < ApplicationController
    def index
      @movie_count = Core::Movie.count
      @actor_count = Core::Actor.count
      @casting_count = Core::Casting.count
    end
  end
end

admin/app/controllers/admin/movies_controller.rb
require_dependency "admin/application_controller"

module Admin
  class MoviesController < ApplicationController
    before_filter :lookup_movie, only: [:show, :edit, :update, :destroy]

    def index
      @movies = Core::Movie.all
    end

    def new
      @movie = Core::Movie.new
    end

    def create
      @movie = Core::Movie.new(movie_params)
      if @movie.save
        redirect_to action: :index
      else
        render :new
      end
    end

    def show
    end

    def edit
    end

    def update
      @movie = Core::Movie.find(params[:id])

      if @movie.update(movie_params)
        redirect_to action: :index
      else
        render :edit
      end
    end

    def destroy
      @movie.destroy!
      redirect_to action: :index
    end

    private
      def movie_params
        params.require(:movie).permit(:title, :production_start, :production_finish, :premiere, :description)
      end

      def lookup_movie
        @movie = Core::Movie.find(params[:id])
      end
  end
end

admin/app/helpers/admin/actors_helper.rb
module Admin
  module ActorsHelper
  end
end

admin/app/helpers/admin/admin_helper.rb
module Admin
  module AdminHelper
    def nav_tab_li(label, link_opts)
      opts = {}
      opts[:class] = 'active' if controller.class.name =~ /#{label}/i
      capture_haml do
        haml_tag("li", opts) do
          haml_tag("a", href: url_for(link_opts)) do
            haml_tag("span", label)
          end
        end
      end
    end

    def formatted(date)
      if date
        date.to_formatted_s(:long)
      else
        "N/A"
      end
    end

    def header_with_add_button(header, button_label, path)
      capture_haml do
        haml_tag(:row) do
          haml_tag(:div, class: 'col-md-10') do
            haml_tag(:h2, header)
          end
          haml_tag(:div, class: 'col-md-2') do
            haml_tag(:h2) do
              haml_tag(:a, href: path, class: 'btn btn-primary') do
                haml_tag(:span, button_label)
              end
            end
          end
        end
      end
    end
  end
end

admin/app/helpers/admin/application_helper.rb
module Admin
  module ApplicationHelper
  end
end

admin/app/helpers/admin/dashboard_helper.rb
module Admin
  module DashboardHelper
  end
end

admin/app/helpers/admin/movies_helper.rb
module Admin
  module MoviesHelper
  end
end

admin/app/views/admin/actors/_actor_form.haml
= bootstrap_form_for(actor) do |form|
  %div.row
    %div.col-md-1
      = form.text_field :id, label: 'ID', disabled: true
    %div.col-md-5
      = form.text_field :first_name
    %div.col-md-6
      = form.text_field :last_name
  = render 'shared/form_controls', form: form, cancel_path: actors_path

admin/app/views/admin/actors/edit.html.haml
%h2 Edit Actor
= render "actor_form", actor: @actor

admin/app/views/admin/actors/index.html.haml
= header_with_add_button("Actors", "Add Actor", new_actor_path)

%table.table.table-striped
  %thead
    %tr
      %td ID
      %td First Name
      %td Last Name
      %td Actions
  - @actors.each do |actor|
    %tr
      %td
        = actor.id
      %td
        = actor.first_name
      %td
        = actor.last_name
      %td
        = render 'shared/list_element_actions', path: actor_path(actor), edit_path: edit_actor_path(actor), except: [:show]

admin/app/views/admin/actors/new.html.haml
%h2 Add Actor
= render "actor_form", actor: @actor

admin/app/views/admin/admin/index.haml
This is a test.

admin/app/views/admin/dashboard/index.html.haml
%h2 Statistics

%div.col-md-4
  %div.metric
    %div.header
      Movies
    %div.value
      = @movie_count

%div.col-md-4
  %div.metric
    %div.header
      Actors
    %div.value
      = @actor_count

%div.col-md-4
  %div.metric
    %div.header
      Castings
    %div.value
      = @casting_count

admin/app/views/admin/movies/_movie_form.haml
= bootstrap_form_for(movie) do |form|
  %div.row
    %div.col-md-1
      = form.text_field :id, label: 'ID', disabled: true
    %div.col-md-11
      = form.text_field :title
  %div.row
    %div.col-md-4
      = form.text_field :production_start, class: 'datepicker'
    %div.col-md-4
      = form.text_field :production_finish, class: 'datepicker'
    %div.col-md-4
      = form.text_field :premiere, label: 'Premiere Date', class: 'datepicker'
  %div.row
    %div.col-md-12
      = form.text_area :description, rows: 6
  = render 'shared/form_controls', form: form, cancel_path: movies_path

admin/app/views/admin/movies/edit.html.haml
%h2 Edit Movie
= render "movie_form", movie: @movie

admin/app/views/admin/movies/index.html.haml
= header_with_add_button("Movies", "Add Movie", new_movie_path)

%table.table.table-striped
  %thead
    %tr
      %td ID
      %td Title
      %td Production Start
      %td Production Finish
      %td Premier
      %td Actions
  - @movies.each do |movie|
    %tr
      %td
        = movie.id
      %td
        = link_to(movie.title, movie)
      %td
        = formatted movie.production_start
      %td
        = formatted movie.production_finish
      %td
        = formatted movie.premiere
      %td
        = render 'shared/list_element_actions', path: movie_path(movie), edit_path: edit_movie_path(movie)

admin/app/views/admin/movies/new.html.haml
%h2 Add Movie
= render "movie_form", movie: @movie

admin/app/views/admin/movies/show.html.haml
%h2
  = @movie.title
%div.row
  %div.col-md-12
    = @movie.description
%div.spacer-20
%div.row
  %div.col-md-4
    Production started on
    = formatted @movie.production_start
  %div.col-md-4
    Production finished on
    = formatted @movie.production_finish
  %div.col-md-4
    Premiered on
    = formatted @movie.premiere
%div.spacer-20
%div.row
  %div.col-md-11
  %div.col-md-1
    = link_to movies_path do
      %span.glyphicon.glyphicon-arrow-left
      Back

admin/app/views/layouts/admin/application.haml
<!DOCTYPE html>
%html(lang="en")
  %head
    %title Hollywood Admin
    = stylesheet_link_tag("admin/application", media: "all")
    = javascript_include_tag("admin/application")
    = csrf_meta_tags
  %body
    .container
      .row.banner
        %h1 Hollywood! Administration
      .row
        %ul.nav.nav-tabs
          = nav_tab_li("Dashboard", {controller: :dashboard})
          = nav_tab_li("Movies", movies_path)
          = nav_tab_li("Actors", actors_path)
          = nav_tab_li("Castings", {})
      .row
        = yield

admin/app/views/shared/_form_controls.haml
%div.row
  %div.col-md-2
    = link_to "Cancel", cancel_path, class: 'btn btn-primary'
  %div.col-md-8
    &#160;
  %div.col-md-2
    = form.submit class: 'btn btn-primary', style: 'float: right'

admin/app/views/shared/_list_element_actions.haml
- except ||= []
- unless except.include? :show
  = link_to path do
    %span.glyphicon.glyphicon-zoom-in
- unless except.include? :edit
  = link_to edit_path do
    %span.glyphicon.glyphicon-pencil
- unless except.include? :delete
  = link_to path, method: :delete do
    %span.glyphicon.glyphicon-trash